### ISSUE TITLE
Minc2.0 support

### ISSUE THREAD

**Issue by cfhammill** [stnava/ITKR#10]
Hi All,

Thanks for the wonderful package. I was wondering if it would be possible to incorporate minc2.0 support into ITKR.  There is a [package by Baghdadi](http://www.insight-journal.org/browse/publication/88) that provides the IO wrappers necessary to read/write minc files. 

Thanks again,

Chris

**Comment by cfhammill** [comment]
@vfonov Would you know how to implement this here as you did for minc-toolkit-v2?

**Comment by vfonov** [comment]
not sure what's the problem , ITK have MINC2 IO built in, since quite a long time ago

**Comment by cfhammill** [comment]
Interesting, thanks Vlad. Looks like one of the cmake flags in configure is <inadvertantly> disabling mincIO.

```
cmake \
    -DCMAKE_BUILD_TYPE:STRING="${CMAKE_BUILD_TYPE}" \
    -DCMAKE_C_FLAGS="${CMAKE_C_FLAGS} -Wno-c++11-long-long -fPIC -O2 -DNDEBUG  "\
    -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -Wno-c++11-long-long -fPIC -O2 -DNDEBUG  "\
    -DITK_USE_GIT_PROTOCOL:BOOL=OFF \
    -DBUILD_SHARED_LIBS=OFF \
    -DBUILD_TESTING:BOOL=OFF \
    -DBUILD_EXAMPLES:BOOL=OFF \
    -DCMAKE_INSTALL_PREFIX:PATH=${R_PACKAGE_DIR}/libs/  \
    -DITK_LEGACY_REMOVE:BOOL=OFF  \
    -DITK_FUTURE_LEGACY_REMOVE:=BOOL=ON \
    -DITKV3_COMPATIBILITY:BOOL=ON \
    -DITK_BUILD_DEFAULT_MODULES:BOOL=OFF \
    -DKWSYS_USE_MD5:BOOL=ON \
    -DITK_WRAPPING:BOOL=OFF \
    -DModule_MGHIO:BOOL=ON \
    -DModule_ITKDeprecated:BOOL=OFF \
    -DModule_ITKReview:BOOL=ON \
    -DModule_ITKVtkGlue:BOOL=OFF \
    -D ITKGroup_Core=ON \
    -D Module_ITKReview=ON \
    -D ITKGroup_Filtering=ON \
    -D ITKGroup_IO=ON \
    -D ITKGroup_Numerics=ON \
    -D ITKGroup_Registration=ON \
    -D ITKGroup_Segmentation=ON ../itks/
```

Not sure which one, looks like it should be brought in by ITKGroup_IO=ON, maybe the ITKv3 compatibility?

**Comment by cfhammill** [comment]
I can enable building RMINC by adding:

```
    -D Module_ITKMINC=ON \
    -D Module_ITKIOMINC=ON \
    -D  Module_ITKIOTransformMINC=ON \
```

Although this causes a segfault in ANTsR when trying to load a minc volume

```
library(ANTsR)
antsImageRead("~/MR160_105-9999-01_002_t1.mnc")

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: .Call("antsImageHeaderInfo", filename, PACKAGE = "ANTsR")
 2: antsImageHeaderInfo(filename)
 3: antsImageRead("~/MR160_105-9999-01_002_t1.mnc")
```

Which I suspect has something to do with ITK not being build properly. Although it could be in ANTsR.

**Comment by vfonov** [comment]
probably antsImageHeaderInfo get much more then it expects to find - MINCs have lots of information in the header.

**Comment by vfonov** [comment]
what's the output of mincinfo MR160_105-9999-01_002_t1.mnc ?

**Comment by cfhammill** [comment]
Certainly seems like a possibility. If you think the issue is in ANTsR, not ITKR, I can issue a pull request with the new cmake variables and I can move this issue over to ANTsR.

As for mincinfo:

```
file: /home/chammill/MR160_105-9999-01_002_t1.mnc
image: signed__ short 0 to 1022
image dimensions: xspace zspace yspace
    dimension name         length         step        start
    --------------         ------         ----        -----
    xspace                    192            1     -91.1134
    zspace                    256            1     -151.428
    yspace                    240           -1      113.814
```

**Comment by stnava** [comment]
could it be related to the type ... can you try a float image?


brian

**Comment by vfonov** [comment]
looks like something is up here: https://github.com/stnava/ANTsR/blob/master/src/antsImageHeaderInfo.cpp#L8

The image type most likely will be identified as float by ITK, here short is used to describe how file is stored on disk.

**Comment by cfhammill** [comment]
I converted the volume to both float and double to no avail. Should I move this over to ANTsR?
