### ISSUE TITLE
I have issue to install your package

### ISSUE THREAD

**Issue by billchenxi** [stnava/ITKR#11]
> devtools::install_github( "stnava/ITKR" )
Downloading GitHub repo stnava/ITKR@master
from URL https://api.github.com/repos/stnava/ITKR/zipball/master
Installing ITKR
'/Library/Frameworks/R.framework/Resources/bin/R' CMD INSTALL '/private/var/folders/96/7b7c46zx7v1fqqrsmw_0btx40000gn/T/Rtmpc0c6ZL/devtools1055e4944128f/stnava-ITKR-8d84bf1' 
Your branch is up-to-date with 'origin/master'.
Installation failed: Command failed:
 '/Library/Frameworks/R.framework/Resources/bin/R' CMD INSTALL '/private/var/folders/96/7b7c46zx7v1fqqrsmw_0btx40000gn/T/Rtmpc0c6ZL/devtools1055e4944128f/stnava-ITKR-8d84bf1'  
 * installing to library ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library’
* installing *source* package ‘ITKR’ ...
Cloning into 'itks'...
Checking out files: 100% (15235/15235), done.
Already on 'master'
Note: checking out '2714cc1805f50504f5b9a60d0f62ffec8e73989'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 2714cc1... Merge topic 'setupForDevelopment-absolute-path'
./configure: line 26: cmake: command not found
ERROR: configuration failed for package ‘ITKR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/ITKR’

**Comment by billchenxi** [comment]
Also the tools and methods packages are not available for R 3.2, are they needed for the instllation? If so, can you help me to find them?
Thanks,

**Comment by sremedios** [comment]
I'm having the same problem as billchenxi.  Is there a workaround for this issue yet?

**Comment by stnava** [comment]
install cmake or cmaker.

see install instructions here:

https://github.com/stnava/ANTsR/


brian

**Comment by sremedios** [comment]
Wow, I don't know how I didn't realize I was just missing cmake.  Thanks for the quick response; fixed the issue effortlessly with that.

**Comment by muschellij2** [comment]
@stnava Can be closed.
