### ISSUE TITLE
Install fails using any method at end of ITKR.so installation

### ISSUE THREAD

**Issue by chadtj** [stnava/ITKR#2]
This is three R versions we tried, R 3.1.2, 3.2.0, and 3.2.2 on RHEL 5.
Cmake is in the path and versioned 2.8.9. Gcc is version 4.8.2
It can build seemingly everything except dummy.o and ITKR.so. 
The whole log is attached for completeness, but here are the errors:

I/import/monstrum2/Applications/R3.1.2/lib64/R/include -DNDEBUG  -I/usr/local/include       -c dummy.cpp -o dummy.o
make: I/import/monstrum2/Applications/R3.1.2/lib64/R/include: Command not found
 It seems like part of the gcc command is missing perhaps before -source
.
.

-- Installing: /import/monstrum2/Applications/R3.2.0/lib64/R/library/ITKR/libs/lib/libitkMGHIO-4.8.a
make[1]: Leaving directory `/tmp/RtmpDFrZJY/R.INSTALL2dd87e5981b7/ITKR/src/itkb'
-shared -L/usr/local/lib64 -o ITKR.so dummy.o
/bin/sh: line 2: -shared: command not found
make: *** [ITKR.so] Error 127
ERROR: compilation failed for package 'ITKR'
* removing '/import/monstrum2/Applications/R3.2.0/lib64/R/library/ITKR'
* restoring previous '/import/monstrum2/Applications/R3.2.0/lib64/R/library/ITKR'

The downloaded source packages are in
    '/tmp/RtmpPmhf7z/downloaded_packages'
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("ITKR") :
  installation of package 'ITKR' had non-zero exit status

[ITKR_install_fail.txt](https://github.com/stnava/ITKR/files/39496/ITKR_install_fail.txt)

**Comment by stnava** [comment]
hmm ... i am running a travis build to check this.  but i recently (yesterday) installed ITKR on both fresh OSX and Redhat LINUX flawlessly.  so no way to reproduce your problem on this end.  this part of your note:

```
-shared -L/usr/local/lib64 -o ITKR.so dummy.o
/bin/sh: line 2: -shared: command not found
```

makes it look like a shell issue or somethign like that.  are you using a bash shell?

**Comment by stnava** [comment]
[travis builds successfully](https://travis-ci.org/stnava/ITKR)

so likely there is some problem on your end
