### ISSUE TITLE
Start versioning the releases

### ISSUE THREAD

**Issue by zarquon42b** [stnava/ITKR#3]
To make ANTsR compilable ITKR should have proper realease versions (e.g. 0.0.1). AS ANTsR does not compile properly with the first release we need add a minimum ITKR version in ANTsR's DESCRIPTION files. That way we can maintain releases in drat easily.

**Comment by stnava** [comment]
great! happy to take a pull request

**Comment by zarquon42b** [comment]
I will look into this next week. I am also planning on updating the drat repo accordingly.
