### ISSUE TITLE
ITKR ANTsCore clang issue

### ISSUE THREAD

**Issue by muschellij2** [stnava/ITKR#39]
So ITKR release was 3 months ago: https://travis-ci.org/stnava/ITKR/builds/526934364.  That built with `clang 5.0.0`: https://travis-ci.org/stnava/ITKR/jobs/526934365#L51 on linux but ANTsRCore is using `clang 7.0.0` https://travis-ci.org/ANTsX/ANTsRCore/jobs/571879619#L51.  A new release is needed to keep them in sync I think.  This can also be due to the fact that ITKR built on trusty: https://travis-ci.org/stnava/ITKR/jobs/526934365#L9, but this is building on `xenial`: https://travis-ci.org/ANTsX/ANTsRCore/jobs/571879619#L9

See the defaults on: https://docs.travis-ci.com/user/languages/c/#clang-on-linux

**Comment by muschellij2** [comment]
This is the issue with `robex` for failing. For @muschellij2  only

**Comment by muschellij2** [comment]
FYI - what needs to happen here is to simply build another binary aka push a tag so that the downstream packages work.

@dorianps @jeffduda @stnava

**Comment by stnava** [comment]
I believe this has been addressed.
