### ISSUE TITLE
ITKR installation failed due to "--no-staged-install"

### ISSUE THREAD

**Issue by yingzhang121** [stnava/ITKR#41]
Hi, Developer,

I tried to install ITKR in latest R (v3.6.1), then the installation failed due to the following error:
hard-coded installation path: please report to the package maintainer and use ‘--no-staged-install’

When I googled this error, I was directed to this page:
https://community.rstudio.com/t/no-staged-install-error/35321

As a summary, in the latest R, there is a new option R for the Staged Install check, which becomes one of the common sources of the error. It also gives an solution, "The announcement also mentions that you can opt out of the check by adding StagedInstall: no to your DESCRIPTION file. Maybe that will work better than the flag --no-staged-install."

So could you make the necessary change?

Best,
Ying

**Comment by danieladamspencer** [comment]
Hey Ying,

A quick fix is to pull and add the line yourself, which is what I ended up doing. Adding StagedInstall: no fixed the issue for me completely. I understand that this is not the best practice going forward, but it will keep you in business today.

Best,
Dan
