### ISSUE TITLE
unable to install ITKR under Ubuntu 22.04LTS / R 4.2.0

### ISSUE THREAD

**Issue by JPolzehl** [stnava/ITKR#59]
I'm trying to install ITKR under Ubuntu 22.04LTS / R 4.2.0 within a terminal session following the instructions in
https://johnmuschelli.com/neuroc/installing_ANTsR/index.html
all prerequisites listed in  https://itk.org/Wiki/ITK/Prerequisites are installed
The installation process runs smoothly until 

[ 83%] Building CXX object Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/CMakeFiles/gdcmMSFF.dir/gdcmImageChangePhotometricInterpretation.cxx.o
In file included from /tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itks/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageChangePhotometricInterpretation.cxx:14:
/tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itks/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageChangePhotometricInterpretation.h: In function ‘T gdcm::Clamp(int)’:
/tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itks/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageChangePhotometricInterpretation.h:67:32: error: ‘numeric_limits’ is not a member of ‘std’
   67 |   return v < 0 ? 0 : (v > std::numeric_limits<T>::max() ? std::numeric_limits<T>::max() : v);
      |                                ^~~~~~~~~~~~~~
/tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itks/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageChangePhotometricInterpretation.h:67:48: error: expected primary-expression before ‘>’ token
   67 |   return v < 0 ? 0 : (v > std::numeric_limits<T>::max() ? std::numeric_limits<T>::max() : v);
      |                                                ^
/tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itks/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageChangePhotometricInterpretation.h:67:51: error: ‘::max’ has not been declared; did you mean ‘std::max’?
   67 |   return v < 0 ? 0 : (v > std::numeric_limits<T>::max() ? std::numeric_limits<T>::max() : v);
      |                                                   ^~~
      |                                                   std::max
In file included from /usr/include/c++/11/algorithm:62,
                 from /tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itks/Modules/ThirdParty/GDCM/src/gdcm/Source/DataStructureAndEncodingDefinition/gdcmByteValue.h:24,
                 from /tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itks/Modules/ThirdParty/GDCM/src/gdcm/Source/DataStructureAndEncodingDefinition/gdcmDataElement.h:20,
                 from /tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itks/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmBitmap.h:19,
                 from /tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itks/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmBitmapToBitmapFilter.h:17,
                 from /tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itks/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmPixmapToPixmapFilter.h:17,
                 from /tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itks/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageToImageFilter.h:17,
                 from /tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itks/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageChangePhotometricInterpretation.h:17,
                 from /tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itks/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageChangePhotometricInterpretation.cxx:14:
/usr/include/c++/11/bits/stl_algo.h:3467:5: note: ‘std::max’ declared here
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
In file included from /tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itks/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageChangePhotometricInterpretation.cxx:14:
/tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itks/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageChangePhotometricInterpretation.h:67:64: error: ‘numeric_limits’ is not a member of ‘std’
   67 |   return v < 0 ? 0 : (v > std::numeric_limits<T>::max() ? std::numeric_limits<T>::max() : v);
      |                                                                ^~~~~~~~~~~~~~
/tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itks/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageChangePhotometricInterpretation.h:67:80: error: expected primary-expression before ‘>’ token
   67 |   return v < 0 ? 0 : (v > std::numeric_limits<T>::max() ? std::numeric_limits<T>::max() : v);
      |                                                                                ^
/tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itks/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageChangePhotometricInterpretation.h:67:83: error: ‘::max’ has not been declared; did you mean ‘std::max’?
   67 |   return v < 0 ? 0 : (v > std::numeric_limits<T>::max() ? std::numeric_limits<T>::max() : v);
      |                                                                                   ^~~
      |                                                                                   std::max
In file included from /usr/include/c++/11/algorithm:62,
                 from /tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itks/Modules/ThirdParty/GDCM/src/gdcm/Source/DataStructureAndEncodingDefinition/gdcmByteValue.h:24,
                 from /tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itks/Modules/ThirdParty/GDCM/src/gdcm/Source/DataStructureAndEncodingDefinition/gdcmDataElement.h:20,
                 from /tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itks/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmBitmap.h:19,
                 from /tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itks/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmBitmapToBitmapFilter.h:17,
                 from /tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itks/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmPixmapToPixmapFilter.h:17,
                 from /tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itks/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageToImageFilter.h:17,
                 from /tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itks/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageChangePhotometricInterpretation.h:17,
                 from /tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itks/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageChangePhotometricInterpretation.cxx:14:
/usr/include/c++/11/bits/stl_algo.h:3467:5: note: ‘std::max’ declared here
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-c++11-long-long’ may have been intended to silence earlier diagnostics
make[3]: *** [Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/CMakeFiles/gdcmMSFF.dir/build.make:482: Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/CMakeFiles/gdcmMSFF.dir/gdcmImageChangePhotometricInterpretation.cxx.o] Fehler 1
make[3]: *** Auf noch nicht beendete Prozesse wird gewartet …
make[3]: Verzeichnis „/tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itkb“ wird betreten
make[3]: Verzeichnis „/tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itkb“ wird verlassen
[ 83%] Built target ITKCommon-all
make[3]: Verzeichnis „/tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itkb“ wird betreten
make[3]: Verzeichnis „/tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itkb“ wird verlassen
make[3]: Verzeichnis „/tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itkb“ wird betreten
[ 83%] Building CXX object Modules/Numerics/Statistics/src/CMakeFiles/ITKStatistics.dir/itkProbabilityDistribution.cxx.o
make[3]: Verzeichnis „/tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itkb“ wird verlassen
make[2]: *** [CMakeFiles/Makefile2:8100: Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/CMakeFiles/gdcmMSFF.dir/all] Fehler 2
make[2]: *** Auf noch nicht beendete Prozesse wird gewartet …
[ 83%] Building CXX object Modules/Numerics/Statistics/src/CMakeFiles/ITKStatistics.dir/itkDenseFrequencyContainer2.cxx.o
[ 83%] Building CXX object Modules/Numerics/Statistics/src/CMakeFiles/ITKStatistics.dir/itkSparseFrequencyContainer2.cxx.o
[ 83%] Building CXX object Modules/Numerics/Statistics/src/CMakeFiles/ITKStatistics.dir/itkChiSquareDistribution.cxx.o
[ 83%] Building CXX object Modules/Numerics/Statistics/src/CMakeFiles/ITKStatistics.dir/itkGaussianDistribution.cxx.o
[ 83%] Building CXX object Modules/Numerics/Statistics/src/CMakeFiles/ITKStatistics.dir/itkTDistribution.cxx.o
[ 83%] Building CXX object Modules/Numerics/Statistics/src/CMakeFiles/ITKStatistics.dir/itkNormalVariateGenerator.cxx.o
[ 83%] Building CXX object Modules/Numerics/Statistics/src/CMakeFiles/ITKStatistics.dir/itkDecisionRule.cxx.o
[ 83%] Building CXX object Modules/Numerics/Statistics/src/CMakeFiles/ITKStatistics.dir/itkMaximumDecisionRule.cxx.o
[ 83%] Building CXX object Modules/Numerics/Statistics/src/CMakeFiles/ITKStatistics.dir/itkMaximumRatioDecisionRule.cxx.o
[ 83%] Building CXX object Modules/Numerics/Statistics/src/CMakeFiles/ITKStatistics.dir/itkMinimumDecisionRule.cxx.o
[ 83%] Building CXX object Modules/Numerics/Statistics/src/CMakeFiles/ITKStatistics.dir/itkHistogramToRunLengthFeaturesFilter.cxx.o
[ 84%] Building CXX object Modules/Numerics/Statistics/src/CMakeFiles/ITKStatistics.dir/itkExpectationMaximizationMixtureModelEstimator.cxx.o
[ 84%] Building CXX object Modules/Numerics/Statistics/src/CMakeFiles/ITKStatistics.dir/itkHistogramToTextureFeaturesFilter.cxx.o
[ 84%] Linking CXX static library ../../../../lib/libITKStatistics-5.1.a
make[3]: Verzeichnis „/tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itkb“ wird verlassen
[ 84%] Built target ITKStatistics
make[2]: Verzeichnis „/tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itkb“ wird verlassen
make[1]: *** [Makefile:156: all] Fehler 2
make[1]: Verzeichnis „/tmp/RtmpPfsR7Z/R.INSTALL1c9326c026db3/ITKR/src/itkb“ wird verlassen
make: *** [Makevars:8: libs] Fehler 2
ERROR: compilation failed for package ‘ITKR’
* removing ‘/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR’

Die heruntergeladenen Quellpakete sind in 
	‘/tmp/RtmpjGwRv8/downloaded_packages’
Warnmeldungen:
1: In (function (pkgs, lib, repos = getOption("repos"), contriburl = contrib.url(repos,  :
  Installation des Pakets ‘ITKR’ hatte Exit-Status ungleich 0
2: In neuro_install(...) :
  Package(s): ITKR released binaries/sources were not installed, please try to install with release_repo = "github"

====================================================================================
Session status:

devtools::session_info()
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.0 (2022-04-22)
 os       TUXEDO OS
 system   x86_64, linux-gnu
 ui       X11
 language
 collate  de_DE.UTF-8
 ctype    de_DE.UTF-8
 tz       America/Chicago
 date     2022-06-07
 pandoc   NA

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date (UTC) lib source
 BiocManager   1.30.18 2022-05-18 [1] CRAN (R 4.2.0)
 brio          1.1.3   2021-11-30 [1] CRAN (R 4.2.0)
 cachem        1.0.6   2021-08-19 [1] CRAN (R 4.2.0)
 callr         3.7.0   2021-04-20 [1] CRAN (R 4.2.0)
 cli           3.3.0   2022-04-25 [1] CRAN (R 4.2.0)
 crayon        1.5.1   2022-03-26 [1] CRAN (R 4.2.0)
 desc          1.4.1   2022-03-06 [1] CRAN (R 4.2.0)
 devtools      2.4.3   2021-11-30 [1] CRAN (R 4.2.0)
 ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.2.0)
 fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.2.0)
 fs            1.5.2   2021-12-08 [1] CRAN (R 4.2.0)
 glue          1.6.2   2022-02-24 [1] CRAN (R 4.2.0)
 lifecycle     1.0.1   2021-09-24 [1] CRAN (R 4.2.0)
 magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.2.0)
 memoise       2.0.1   2021-11-26 [1] CRAN (R 4.2.0)
 pkgbuild      1.3.1   2021-12-20 [1] CRAN (R 4.2.0)
 pkgload       1.2.4   2021-11-30 [1] CRAN (R 4.2.0)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.2.0)
 processx      3.5.3   2022-03-25 [1] CRAN (R 4.2.0)
 ps            1.7.0   2022-04-23 [1] CRAN (R 4.2.0)
 purrr         0.3.4   2020-04-17 [1] CRAN (R 4.2.0)
 R6            2.5.1   2021-08-19 [1] CRAN (R 4.2.0)
 remotes       2.4.2   2021-11-30 [1] CRAN (R 4.2.0)
 rlang         1.0.2   2022-03-04 [1] CRAN (R 4.2.0)
 rprojroot     2.0.3   2022-04-02 [1] CRAN (R 4.2.0)
 sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.2.0)
 testthat      3.1.4   2022-04-26 [1] CRAN (R 4.2.0)
 usethis       2.1.6   2022-05-25 [1] CRAN (R 4.2.0)
 withr         2.5.0   2022-03-03 [1] CRAN (R 4.2.0)

 [1] /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2
 [2] /usr/local/lib/R/library

**Comment by JPolzehl** [comment]
CMake version installed is 3.22.1

**Comment by stnava** [comment]
try latest version v0.6.0.0.1

**Comment by JPolzehl** [comment]
thanks, manual installation from git works.
For convenience it would help if 
neuro_install('ITKR', release = "current", release_repo = "github") 
would point to this version, in the moment this provides an error: incorrect version specification 'NA'
