### ISSUE TITLE
ITK-4.11 or ITK-4.9?

### ISSUE THREAD

**Issue by agt24** [stnava/ITKR#8]
I'm having some trouble installing ANTsR with the recommended devtools command:
`(devtools::install_github( "stnava/ANTsR" )`

The configure script appears to run ITKR::itkVersion() to find the ITK include directories. It returns 4.11, but all of the files the ITKR installation (which occurred immediately before) are labelled ITK-4.9:

```
> ITKR::itkIncludes()
[1] "itkIncludes: itk includes do not exist"
/home/adamt/R/x86_64-pc-linux-gnu-library/3.3/ITKR/libs/include/ITK-4.11/> ITKR::itkVersion()
[1] "4.11"
> system("ls /home/adamt/R/x86_64-pc-linux-gnu-library/3.3/ITKR/libs/include/")
ITK-4.9
> 
```

Any ideas on the cause of the mismatch?

**Comment by stnava** [comment]
this is a bug.


brian

**Comment by agt24** [comment]
Thanks for the quick reply. Should I fall back to v0.0.1-alpha? Or is there a quicker workaround?

**Comment by stnava** [comment]
​am updating ants, itkr and antsr to 4.11 now.  it may be fixed in latest
set of pushes.   am testing on osx/linux/travis so we'll see soon.


brian

**Comment by agt24** [comment]
Seems to work now. Thanks.

**Comment by muschellij2** [comment]
@stnava you can close this.
